services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      
  directus:
    image: directus/directus:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8055:8055"
    environment:
      DB_CLIENT: pg
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: directus
      KEY: "directus-key"
      SECRET: "directus-secret"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin"
    volumes:
      - directus_uploads:/directus/uploads
      - directus_extensions:/directus/extensions
volumes:
  directus_uploads:
  directus_extensions:
